# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(565, 559)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 541, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.word_to_pdf = QtWidgets.QGroupBox(self.tab)
        self.word_to_pdf.setGeometry(QtCore.QRect(10, 10, 511, 161))
        self.word_to_pdf.setObjectName("word_to_pdf")
        self.word_file_name = QtWidgets.QLabel(self.word_to_pdf)
        self.word_file_name.setGeometry(QtCore.QRect(110, 30, 200, 30))
        self.word_file_name.setText("")
        self.word_file_name.setObjectName("word_file_name")
        self.pdf_save_path_text = QtWidgets.QTextBrowser(self.word_to_pdf)
        self.pdf_save_path_text.setEnabled(False)
        self.pdf_save_path_text.setGeometry(QtCore.QRect(20, 120, 270, 30))
        self.pdf_save_path_text.setObjectName("pdf_save_path_text")
        self.pdf_save_path = QtWidgets.QToolButton(self.word_to_pdf)
        self.pdf_save_path.setGeometry(QtCore.QRect(20, 80, 80, 30))
        self.pdf_save_path.setObjectName("pdf_save_path")
        self.word_to_pdf_Button = QtWidgets.QToolButton(self.word_to_pdf)
        self.word_to_pdf_Button.setGeometry(QtCore.QRect(380, 20, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.word_to_pdf_Button.setFont(font)
        self.word_to_pdf_Button.setObjectName("word_to_pdf_Button")
        self.word_file = QtWidgets.QPushButton(self.word_to_pdf)
        self.word_file.setGeometry(QtCore.QRect(20, 30, 80, 30))
        self.word_file.setObjectName("word_file")
        self.pdf_to_word = QtWidgets.QGroupBox(self.tab)
        self.pdf_to_word.setGeometry(QtCore.QRect(10, 190, 511, 161))
        self.pdf_to_word.setObjectName("pdf_to_word")
        self.pdf_file = QtWidgets.QToolButton(self.pdf_to_word)
        self.pdf_file.setGeometry(QtCore.QRect(20, 30, 80, 30))
        self.pdf_file.setObjectName("pdf_file")
        self.word_save_path = QtWidgets.QToolButton(self.pdf_to_word)
        self.word_save_path.setGeometry(QtCore.QRect(20, 80, 80, 30))
        self.word_save_path.setObjectName("word_save_path")
        self.word_save_path_text = QtWidgets.QTextBrowser(self.pdf_to_word)
        self.word_save_path_text.setEnabled(False)
        self.word_save_path_text.setGeometry(QtCore.QRect(20, 120, 270, 30))
        self.word_save_path_text.setObjectName("word_save_path_text")
        self.pdf_file_name = QtWidgets.QLabel(self.pdf_to_word)
        self.pdf_file_name.setGeometry(QtCore.QRect(120, 30, 150, 30))
        self.pdf_file_name.setText("")
        self.pdf_file_name.setObjectName("pdf_file_name")
        self.pdf_to_word_Button = QtWidgets.QToolButton(self.pdf_to_word)
        self.pdf_to_word_Button.setGeometry(QtCore.QRect(380, 30, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pdf_to_word_Button.setFont(font)
        self.pdf_to_word_Button.setObjectName("pdf_to_word_Button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.word_file.pressed.connect(self.word_file_name.update)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.word_to_pdf.setTitle(_translate("Form", "word转换pdf"))
        self.pdf_save_path.setText(_translate("Form", "存储路径"))
        self.word_to_pdf_Button.setText(_translate("Form", "转换"))
        self.word_file.setText(_translate("Form", "选择文件"))
        self.pdf_to_word.setTitle(_translate("Form", "pdf转换word"))
        self.pdf_file.setText(_translate("Form", "选择文件"))
        self.word_save_path.setText(_translate("Form", "存储路径"))
        self.pdf_to_word_Button.setText(_translate("Form", "转换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "文件转换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "时间戳转换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "二维码生成"))
